apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: knatarasan/todo
          name: todo
          ports:
            - containerPort: 8000
              name: gunicorn
      imagePullSecrets:
        - name: dockersecret
