apiVersion: v1
kind: Service
metadata:
  labels:
    app: django
  name: django
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30487
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django
  type: NodePort
